version: "3.2"

services:
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8070:8080
    networks:
      - app-net
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./build/Dockerfile
    restart: on-failure
    volumes:
      - ./migrationz:/home/app/migrations
      - ./bin:/home/app/bin
      - ./tests:/home/app/tests
      - ./src:/home/app/src
      - ./statics:/home/app/statics
      - ./manage.py:/home/app/manage.py
      - ./setup.py:/home/app/setup.py
    env_file:
      - env/.env.auth
    healthcheck:
      test: curl --fail -s auth:5000/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - auth_db
      - auth_kafka
      - auth_zookeeper
    networks:
      - app-net
  auth_db:
    container_name: auth_db
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.auth_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - app-net
  auth_kafka:
    container_name: auth_kafka
    image: wurstmeister/kafka:latest
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - env/.env.auth_kafka
    depends_on:
      - auth_zookeeper
    networks:
      - app-net
  auth_zookeeper:
    container_name: auth_zookeeper
    image: wurstmeister/zookeeper:latest
    restart: on-failure
    env_file:
      - env/.env.auth_zookeeper
    networks:
      - app-net
volumes:
  db_data:
networks:
  app-net:
    driver: bridge